

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	int32_t capacity;
	int32_t len;
	uint8_t *data;
} RustBuffer;

typedef int32_t (*ForeignCallback)(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);

// Task defined in Rust that Go executes
typedef void (*RustTaskCallback)(const void *, int8_t);

// Callback to execute Rust tasks using a Go routine
//
// Args:
//   executor: ForeignExecutor lowered into a uint64_t value
//   delay: Delay in MS
//   task: RustTaskCallback to call
//   task_data: data to pass the task callback
typedef int8_t (*ForeignExecutorCallback)(uint64_t, uint32_t, RustTaskCallback, void *);

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

// Continuation callback for UniFFI Futures
typedef void (*RustFutureContinuation)(void * , int8_t);

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

// Needed because we can't execute the callback directly from go.
void cgo_rust_task_callback_bridge_rustpushgo(RustTaskCallback, const void *, int8_t);

int8_t uniffiForeignExecutorCallbackrustpushgo(uint64_t, uint32_t, RustTaskCallback, void*);

void uniffiFutureContinuationCallbackrustpushgo(void*, int8_t);

void uniffi_rustpushgo_fn_free_client(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_cloud_diag_full_count(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_cloud_download_attachment(
	void* ptr,
	RustBuffer record_name,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_cloud_download_attachment_avid(
	void* ptr,
	RustBuffer record_name,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_cloud_download_group_photo(
	void* ptr,
	RustBuffer record_name,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_cloud_dump_chats_json(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_cloud_fetch_recent_messages(
	void* ptr,
	uint64_t since_timestamp_ms,
	RustBuffer chat_id,
	uint32_t max_pages,
	uint32_t max_results,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_cloud_query_attachments_fallback(
	void* ptr,
	RustBuffer known_record_names,
	RustCallStatus* out_status
);

int8_t uniffi_rustpushgo_fn_method_client_cloud_supports_avid_download(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_cloud_sync_attachments(
	void* ptr,
	RustBuffer continuation_token,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_cloud_sync_chats(
	void* ptr,
	RustBuffer continuation_token,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_cloud_sync_messages(
	void* ptr,
	RustBuffer continuation_token,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_debug_recoverable_zones(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_delete_cloud_chats(
	void* ptr,
	RustBuffer chat_ids,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_delete_cloud_messages(
	void* ptr,
	RustBuffer message_ids,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_fetch_profile(
	void* ptr,
	RustBuffer record_key,
	RustBuffer decryption_key,
	int8_t has_poster,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_findmy_friends_import(
	void* ptr,
	int8_t daemon,
	RustBuffer url,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_findmy_friends_refresh_json(
	void* ptr,
	int8_t daemon,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_findmy_phone_refresh_json(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_get_contacts_url(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_get_dsid(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_get_facetime_client(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_get_findmy_client(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_get_handles(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_get_icloud_auth_headers(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_get_passwords_client(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_get_registered_services(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_get_sharedstreams_client(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_get_statuskit_client(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_init_statuskit(
	void* ptr,
	uint64_t callback,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_invite_to_status_sharing(
	void* ptr,
	RustBuffer sender_handle,
	RustBuffer handles,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_list_recoverable_chats(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_list_recoverable_message_guids(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_purge_recoverable_zones(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_reset_cloud_client(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_reset_sharedstreams_client(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_method_client_reset_statuskit_cursors(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_resolve_handle(
	void* ptr,
	RustBuffer handle,
	RustBuffer known_handles,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_resolve_handle_cached(
	void* ptr,
	RustBuffer handle,
	RustBuffer known_handles,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_restore_cloud_chat(
	void* ptr,
	RustBuffer record_name,
	RustBuffer chat_identifier,
	RustBuffer group_id,
	int64_t style,
	RustBuffer service,
	RustBuffer display_name,
	RustBuffer participants,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_retry_mmcs_from_descriptor(
	void* ptr,
	RustBuffer descriptor_json,
	RustBuffer name,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_attachment(
	void* ptr,
	RustBuffer conversation,
	RustBuffer data,
	RustBuffer mime,
	RustBuffer uti_type,
	RustBuffer filename,
	RustBuffer handle,
	RustBuffer reply_guid,
	RustBuffer reply_part,
	RustBuffer body,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_change_participants(
	void* ptr,
	RustBuffer conversation,
	RustBuffer new_participants,
	uint64_t group_version,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_delivery_receipt(
	void* ptr,
	RustBuffer conversation,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_edit(
	void* ptr,
	RustBuffer conversation,
	RustBuffer target_uuid,
	uint64_t edit_part,
	RustBuffer new_text,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_error_message(
	void* ptr,
	RustBuffer conversation,
	RustBuffer for_uuid,
	uint64_t error_status,
	RustBuffer status_str,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_icon_change(
	void* ptr,
	RustBuffer conversation,
	RustBuffer photo_data,
	uint64_t group_version,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_icon_clear(
	void* ptr,
	RustBuffer conversation,
	uint64_t group_version,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_mark_unread(
	void* ptr,
	RustBuffer conversation,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_message(
	void* ptr,
	RustBuffer conversation,
	RustBuffer text,
	RustBuffer html,
	RustBuffer handle,
	RustBuffer reply_guid,
	RustBuffer reply_part,
	RustBuffer scheduled_ms,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_message_read_on_device(
	void* ptr,
	RustBuffer conversation,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_move_to_recycle_bin(
	void* ptr,
	RustBuffer conversation,
	RustBuffer handle,
	RustBuffer chat_guid,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_notify_anyways(
	void* ptr,
	RustBuffer conversation,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_peer_cache_invalidate(
	void* ptr,
	RustBuffer conversation,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_permanent_delete_chat(
	void* ptr,
	RustBuffer conversation,
	RustBuffer chat_guid,
	int8_t is_scheduled,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_permanent_delete_messages(
	void* ptr,
	RustBuffer conversation,
	RustBuffer message_uuids,
	int8_t is_scheduled,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_read_receipt(
	void* ptr,
	RustBuffer conversation,
	RustBuffer handle,
	RustBuffer for_uuid,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_recover_chat(
	void* ptr,
	RustBuffer conversation,
	RustBuffer handle,
	RustBuffer chat_guid,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_rename_group(
	void* ptr,
	RustBuffer conversation,
	RustBuffer new_name,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_set_transcript_background(
	void* ptr,
	RustBuffer conversation,
	uint64_t group_version,
	RustBuffer image_data,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_share_profile(
	void* ptr,
	RustBuffer conversation,
	RustBuffer cloud_kit_record_key,
	RustBuffer cloud_kit_decryption_record_key,
	RustBuffer low_res_wallpaper_tag,
	RustBuffer wallpaper_tag,
	RustBuffer message_tag,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_sms_activation(
	void* ptr,
	RustBuffer conversation,
	int8_t enable,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_sms_confirm_sent(
	void* ptr,
	RustBuffer conversation,
	int8_t sms_status,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_tapback(
	void* ptr,
	RustBuffer conversation,
	RustBuffer target_uuid,
	uint64_t target_part,
	uint32_t reaction,
	RustBuffer emoji,
	int8_t remove,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_typing(
	void* ptr,
	RustBuffer conversation,
	int8_t typing,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_typing_with_app(
	void* ptr,
	RustBuffer conversation,
	int8_t typing,
	RustBuffer handle,
	RustBuffer bundle_id,
	RustBuffer icon,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_unschedule(
	void* ptr,
	RustBuffer conversation,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_unsend(
	void* ptr,
	RustBuffer conversation,
	RustBuffer target_uuid,
	uint64_t edit_part,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_update_extension(
	void* ptr,
	RustBuffer conversation,
	RustBuffer for_uuid,
	RustBuffer extension,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_update_profile(
	void* ptr,
	RustBuffer conversation,
	RustBuffer profile,
	int8_t share_contacts,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_update_profile_sharing(
	void* ptr,
	RustBuffer conversation,
	RustBuffer shared_dismissed,
	RustBuffer shared_all,
	uint64_t version,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_set_status(
	void* ptr,
	int8_t active,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_stop(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_subscribe_to_status(
	void* ptr,
	RustBuffer handles,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_test_cloud_messages(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_unsubscribe_all_status(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_validate_targets(
	void* ptr,
	RustBuffer targets,
	RustBuffer handle,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_free_loginsession(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_loginsession_finish(
	void* ptr,
	void* config,
	void* connection,
	RustBuffer existing_identity,
	RustBuffer existing_users,
	RustCallStatus* out_status
);

int8_t uniffi_rustpushgo_fn_method_loginsession_needs_2fa(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_loginsession_submit_2fa(
	void* ptr,
	RustBuffer code,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_free_wrappedapsconnection(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedapsconnection_state(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_free_wrappedapsstate(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_constructor_wrappedapsstate_new(
	RustBuffer string,
	RustCallStatus* out_status
);

RustBuffer uniffi_rustpushgo_fn_method_wrappedapsstate_to_string(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_free_wrappedfacetimeclient(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedfacetimeclient_add_members(
	void* ptr,
	RustBuffer session_id,
	RustBuffer handles,
	int8_t letmein,
	RustBuffer to_members,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedfacetimeclient_bind_bridge_link_to_session(
	void* ptr,
	RustBuffer handle,
	RustBuffer usage,
	RustBuffer group_id,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedfacetimeclient_clear_links(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedfacetimeclient_create_session(
	void* ptr,
	RustBuffer group_id,
	RustBuffer handle,
	RustBuffer participants,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedfacetimeclient_create_session_no_ring(
	void* ptr,
	RustBuffer group_id,
	RustBuffer handle,
	RustBuffer participants,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedfacetimeclient_delete_link(
	void* ptr,
	RustBuffer pseud,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedfacetimeclient_export_state_json(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedfacetimeclient_get_link_for_usage(
	void* ptr,
	RustBuffer handle,
	RustBuffer usage,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedfacetimeclient_get_session_link(
	void* ptr,
	RustBuffer guid,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedfacetimeclient_list_delegated_letmein_requests(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedfacetimeclient_register_pending_ring(
	void* ptr,
	RustBuffer session_id,
	RustBuffer caller_handle,
	RustBuffer targets,
	uint64_t ttl_secs,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedfacetimeclient_remove_members(
	void* ptr,
	RustBuffer session_id,
	RustBuffer handles,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedfacetimeclient_respond_delegated_letmein(
	void* ptr,
	RustBuffer delegation_uuid,
	RustBuffer approved_group,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedfacetimeclient_ring(
	void* ptr,
	RustBuffer session_id,
	RustBuffer targets,
	int8_t letmein,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedfacetimeclient_use_link_for(
	void* ptr,
	RustBuffer old_usage,
	RustBuffer usage,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_free_wrappedfindmyclient(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedfindmyclient_accept_item_share(
	void* ptr,
	RustBuffer circle_id,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedfindmyclient_delete_shared_item(
	void* ptr,
	RustBuffer id,
	int8_t remove_beacon,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedfindmyclient_export_state_json(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedfindmyclient_sync_item_positions(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedfindmyclient_update_beacon_name(
	void* ptr,
	RustBuffer associated_beacon,
	int64_t role_id,
	RustBuffer name,
	RustBuffer emoji,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_free_wrappedidsngmidentity(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_constructor_wrappedidsngmidentity_new(
	RustBuffer string,
	RustCallStatus* out_status
);

RustBuffer uniffi_rustpushgo_fn_method_wrappedidsngmidentity_to_string(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_free_wrappedidsusers(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_constructor_wrappedidsusers_new(
	RustBuffer string,
	RustCallStatus* out_status
);

RustBuffer uniffi_rustpushgo_fn_method_wrappedidsusers_get_handles(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_rustpushgo_fn_method_wrappedidsusers_login_id(
	void* ptr,
	uint64_t i,
	RustCallStatus* out_status
);

RustBuffer uniffi_rustpushgo_fn_method_wrappedidsusers_to_string(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_rustpushgo_fn_method_wrappedidsusers_validate_keystore(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_free_wrappedosconfig(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_rustpushgo_fn_method_wrappedosconfig_get_device_id(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_rustpushgo_fn_method_wrappedosconfig_requires_nac_relay(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_free_wrappedpasswordsclient(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedpasswordsclient_accept_invite(
	void* ptr,
	RustBuffer invite_id,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedpasswordsclient_create_group(
	void* ptr,
	RustBuffer name,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedpasswordsclient_decline_invite(
	void* ptr,
	RustBuffer invite_id,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedpasswordsclient_delete_password_raw_entry(
	void* ptr,
	RustBuffer id,
	RustBuffer group,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedpasswordsclient_export_state_json(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedpasswordsclient_get_password_site_counts(
	void* ptr,
	RustBuffer site,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedpasswordsclient_invite_user(
	void* ptr,
	RustBuffer group_id,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedpasswordsclient_list_password_raw_entry_refs(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedpasswordsclient_query_handle(
	void* ptr,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedpasswordsclient_remove_group(
	void* ptr,
	RustBuffer id,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedpasswordsclient_remove_user(
	void* ptr,
	RustBuffer group_id,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedpasswordsclient_rename_group(
	void* ptr,
	RustBuffer id,
	RustBuffer new_name,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedpasswordsclient_sync_passwords(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedpasswordsclient_upsert_password_raw_entry(
	void* ptr,
	RustBuffer id,
	RustBuffer site,
	RustBuffer account,
	RustBuffer secret_data,
	RustBuffer group,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_free_wrappedsharedstreamsclient(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedsharedstreamsclient_delete_assets(
	void* ptr,
	RustBuffer album,
	RustBuffer assets,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedsharedstreamsclient_download_file(
	void* ptr,
	RustBuffer album,
	RustBuffer asset_guid,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedsharedstreamsclient_export_state_json(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedsharedstreamsclient_get_album_assets(
	void* ptr,
	RustBuffer album,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedsharedstreamsclient_get_album_summary(
	void* ptr,
	RustBuffer album,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedsharedstreamsclient_get_assets_json(
	void* ptr,
	RustBuffer album,
	RustBuffer assets,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedsharedstreamsclient_get_changes(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedsharedstreamsclient_list_album_ids(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedsharedstreamsclient_list_albums(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedsharedstreamsclient_subscribe(
	void* ptr,
	RustBuffer album,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedsharedstreamsclient_subscribe_token(
	void* ptr,
	RustBuffer token,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedsharedstreamsclient_unsubscribe(
	void* ptr,
	RustBuffer album,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_free_wrappedstatuskitclient(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedstatuskitclient_clear_interest_tokens(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedstatuskitclient_export_state_json(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedstatuskitclient_get_known_handles(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedstatuskitclient_invite_to_channel(
	void* ptr,
	RustBuffer sender_handle,
	RustBuffer handles,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedstatuskitclient_request_handles(
	void* ptr,
	RustBuffer handles,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedstatuskitclient_reset_keys(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedstatuskitclient_roll_keys(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedstatuskitclient_share_status(
	void* ptr,
	int8_t active,
	RustBuffer mode,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_free_wrappedtokenprovider(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedtokenprovider_announce_apple_device_if_needed(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedtokenprovider_apple_account_full_name(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedtokenprovider_get_contacts_url(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedtokenprovider_get_dsid(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedtokenprovider_get_escrow_devices(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedtokenprovider_get_icloud_auth_headers(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedtokenprovider_get_mme_delegate_json(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedtokenprovider_join_keychain_clique(
	void* ptr,
	RustBuffer passcode,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedtokenprovider_join_keychain_clique_for_device(
	void* ptr,
	RustBuffer passcode,
	uint32_t device_index,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedtokenprovider_refresh_pet_token(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedtokenprovider_seed_mme_delegate_json(
	void* ptr,
	RustBuffer json,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_init_callback_messagecallback(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_init_callback_statuscallback(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_init_callback_updateuserscallback(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_func_connect(
	void* config,
	void* state,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_func_create_config_from_hardware_key(
	RustBuffer base64_key,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_func_create_config_from_hardware_key_with_device_id(
	RustBuffer base64_key,
	RustBuffer device_id,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_func_create_local_macos_config(
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_func_create_local_macos_config_with_device_id(
	RustBuffer device_id,
	RustCallStatus* out_status
);

uint64_t uniffi_rustpushgo_fn_func_ford_key_cache_size(
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_func_init_logger(
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_func_login_start(
	RustBuffer apple_id,
	RustBuffer password,
	void* config,
	void* connection,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_func_new_client(
	void* connection,
	void* users,
	void* identity,
	void* config,
	RustBuffer token_provider,
	uint64_t message_callback,
	uint64_t update_users_callback,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_func_register_ford_key(
	RustBuffer key,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_func_restore_token_provider(
	void* config,
	void* connection,
	RustBuffer username,
	RustBuffer hashed_password_hex,
	RustBuffer pet,
	RustBuffer spd_base64,
	RustCallStatus* out_status
);

RustBuffer ffi_rustpushgo_rustbuffer_alloc(
	int32_t size,
	RustCallStatus* out_status
);

RustBuffer ffi_rustpushgo_rustbuffer_from_bytes(
	ForeignBytes bytes,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rustbuffer_free(
	RustBuffer buf,
	RustCallStatus* out_status
);

RustBuffer ffi_rustpushgo_rustbuffer_reserve(
	RustBuffer buf,
	int32_t additional,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_continuation_callback_set(
	RustFutureContinuation callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_u8(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_u8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_u8(
	void* handle,
	RustCallStatus* out_status
);

uint8_t ffi_rustpushgo_rust_future_complete_u8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_i8(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_i8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_i8(
	void* handle,
	RustCallStatus* out_status
);

int8_t ffi_rustpushgo_rust_future_complete_i8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_u16(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_u16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_u16(
	void* handle,
	RustCallStatus* out_status
);

uint16_t ffi_rustpushgo_rust_future_complete_u16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_i16(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_i16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_i16(
	void* handle,
	RustCallStatus* out_status
);

int16_t ffi_rustpushgo_rust_future_complete_i16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_u32(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_u32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_u32(
	void* handle,
	RustCallStatus* out_status
);

uint32_t ffi_rustpushgo_rust_future_complete_u32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_i32(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_i32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_i32(
	void* handle,
	RustCallStatus* out_status
);

int32_t ffi_rustpushgo_rust_future_complete_i32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_u64(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_u64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_u64(
	void* handle,
	RustCallStatus* out_status
);

uint64_t ffi_rustpushgo_rust_future_complete_u64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_i64(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_i64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_i64(
	void* handle,
	RustCallStatus* out_status
);

int64_t ffi_rustpushgo_rust_future_complete_i64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_f32(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_f32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_f32(
	void* handle,
	RustCallStatus* out_status
);

float ffi_rustpushgo_rust_future_complete_f32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_f64(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_f64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_f64(
	void* handle,
	RustCallStatus* out_status
);

double ffi_rustpushgo_rust_future_complete_f64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_pointer(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_pointer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_pointer(
	void* handle,
	RustCallStatus* out_status
);

void* ffi_rustpushgo_rust_future_complete_pointer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_rust_buffer(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_rust_buffer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_rust_buffer(
	void* handle,
	RustCallStatus* out_status
);

RustBuffer ffi_rustpushgo_rust_future_complete_rust_buffer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_void(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_void(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_void(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_complete_void(
	void* handle,
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_func_connect(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_func_create_config_from_hardware_key(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_func_create_config_from_hardware_key_with_device_id(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_func_create_local_macos_config(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_func_create_local_macos_config_with_device_id(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_func_ford_key_cache_size(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_func_init_logger(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_func_login_start(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_func_new_client(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_func_register_ford_key(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_func_restore_token_provider(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_cloud_diag_full_count(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_cloud_download_attachment(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_cloud_download_attachment_avid(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_cloud_download_group_photo(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_cloud_dump_chats_json(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_cloud_fetch_recent_messages(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_cloud_query_attachments_fallback(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_cloud_supports_avid_download(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_cloud_sync_attachments(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_cloud_sync_chats(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_cloud_sync_messages(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_debug_recoverable_zones(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_delete_cloud_chats(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_delete_cloud_messages(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_fetch_profile(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_findmy_friends_import(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_findmy_friends_refresh_json(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_findmy_phone_refresh_json(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_get_contacts_url(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_get_dsid(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_get_facetime_client(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_get_findmy_client(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_get_handles(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_get_icloud_auth_headers(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_get_passwords_client(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_get_registered_services(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_get_sharedstreams_client(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_get_statuskit_client(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_init_statuskit(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_invite_to_status_sharing(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_list_recoverable_chats(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_list_recoverable_message_guids(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_purge_recoverable_zones(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_reset_cloud_client(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_reset_sharedstreams_client(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_reset_statuskit_cursors(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_resolve_handle(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_resolve_handle_cached(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_restore_cloud_chat(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_retry_mmcs_from_descriptor(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_attachment(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_change_participants(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_delivery_receipt(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_edit(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_error_message(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_icon_change(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_icon_clear(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_mark_unread(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_message(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_message_read_on_device(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_move_to_recycle_bin(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_notify_anyways(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_peer_cache_invalidate(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_permanent_delete_chat(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_permanent_delete_messages(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_read_receipt(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_recover_chat(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_rename_group(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_set_transcript_background(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_share_profile(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_sms_activation(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_sms_confirm_sent(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_tapback(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_typing(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_typing_with_app(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_unschedule(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_unsend(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_update_extension(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_update_profile(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_update_profile_sharing(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_set_status(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_stop(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_subscribe_to_status(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_test_cloud_messages(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_unsubscribe_all_status(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_validate_targets(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_loginsession_finish(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_loginsession_needs_2fa(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_loginsession_submit_2fa(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedapsconnection_state(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedapsstate_to_string(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedfacetimeclient_add_members(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedfacetimeclient_bind_bridge_link_to_session(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedfacetimeclient_clear_links(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedfacetimeclient_create_session(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedfacetimeclient_create_session_no_ring(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedfacetimeclient_delete_link(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedfacetimeclient_export_state_json(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedfacetimeclient_get_link_for_usage(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedfacetimeclient_get_session_link(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedfacetimeclient_list_delegated_letmein_requests(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedfacetimeclient_register_pending_ring(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedfacetimeclient_remove_members(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedfacetimeclient_respond_delegated_letmein(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedfacetimeclient_ring(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedfacetimeclient_use_link_for(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedfindmyclient_accept_item_share(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedfindmyclient_delete_shared_item(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedfindmyclient_export_state_json(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedfindmyclient_sync_item_positions(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedfindmyclient_update_beacon_name(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedidsngmidentity_to_string(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedidsusers_get_handles(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedidsusers_login_id(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedidsusers_to_string(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedidsusers_validate_keystore(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedosconfig_get_device_id(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedosconfig_requires_nac_relay(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedpasswordsclient_accept_invite(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedpasswordsclient_create_group(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedpasswordsclient_decline_invite(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedpasswordsclient_delete_password_raw_entry(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedpasswordsclient_export_state_json(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedpasswordsclient_get_password_site_counts(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedpasswordsclient_invite_user(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedpasswordsclient_list_password_raw_entry_refs(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedpasswordsclient_query_handle(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedpasswordsclient_remove_group(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedpasswordsclient_remove_user(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedpasswordsclient_rename_group(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedpasswordsclient_sync_passwords(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedpasswordsclient_upsert_password_raw_entry(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedsharedstreamsclient_delete_assets(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedsharedstreamsclient_download_file(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedsharedstreamsclient_export_state_json(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedsharedstreamsclient_get_album_assets(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedsharedstreamsclient_get_album_summary(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedsharedstreamsclient_get_assets_json(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedsharedstreamsclient_get_changes(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedsharedstreamsclient_list_album_ids(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedsharedstreamsclient_list_albums(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedsharedstreamsclient_subscribe(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedsharedstreamsclient_subscribe_token(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedsharedstreamsclient_unsubscribe(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedstatuskitclient_clear_interest_tokens(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedstatuskitclient_export_state_json(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedstatuskitclient_get_known_handles(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedstatuskitclient_invite_to_channel(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedstatuskitclient_request_handles(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedstatuskitclient_reset_keys(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedstatuskitclient_roll_keys(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedstatuskitclient_share_status(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedtokenprovider_announce_apple_device_if_needed(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedtokenprovider_apple_account_full_name(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedtokenprovider_get_contacts_url(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedtokenprovider_get_dsid(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedtokenprovider_get_escrow_devices(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedtokenprovider_get_icloud_auth_headers(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedtokenprovider_get_mme_delegate_json(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedtokenprovider_join_keychain_clique(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedtokenprovider_join_keychain_clique_for_device(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedtokenprovider_refresh_pet_token(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedtokenprovider_seed_mme_delegate_json(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_constructor_wrappedapsstate_new(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_constructor_wrappedidsngmidentity_new(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_constructor_wrappedidsusers_new(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_messagecallback_on_message(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_statuscallback_on_status_update(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_statuscallback_on_keys_received(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_statuscallback_on_reshare_sender(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_updateuserscallback_update_users(
	RustCallStatus* out_status
);

uint32_t ffi_rustpushgo_uniffi_contract_version(
	RustCallStatus* out_status
);


int32_t rustpushgo_cgo_MessageCallback(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t rustpushgo_cgo_StatusCallback(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t rustpushgo_cgo_UpdateUsersCallback(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);

